services:
  postgres:
    image: mirror.gcr.io/postgres
    container_name: postgres
    command: postgres -c listen_addresses=0.0.0.0
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: loftcode
      POSTGRES_INITDB_ARGS: "--auth-host=md5 --auth-local=md5"
    ports:
      - 5432:5432
    volumes:
      # Volume para scripts de inicialização
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
